services:
  db:
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    environment:
      POSTGRES_USER: dummy_postgres_user
      POSTGRES_PASSWORD: dummy_postgres_password
      POSTGRES_DB: drivstoffpriser
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    environment:
      - DB_USER=dummy_postgres_user
      - DB_PASSWORD=dummy_postgres_password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=drivstoffpriser
    volumes:
      - .:/app
      - venv:/app/.venv
    restart: on-failure
    depends_on:
      - db

volumes:
  postgres_data:
  venv:
