"""add covering index for cheapest price sort

Revision ID: 0c8c4dd9b6a2
Revises: 1fb52151a97c
Create Date: 2026-04-21 08:22:26.580807

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c8c4dd9b6a2"
down_revision: str | Sequence[str] | None = "1fb52151a97c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_price_latest_fuel_price",
        "price_registration",
        ["fuel_type", "price"],
        unique=False,
        postgresql_where=sa.text("is_latest = true"),
        postgresql_include=["station_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_price_latest_fuel_price",
        table_name="price_registration",
    )
    # ### end Alembic commands ###
