"""make registered_by nullable

Revision ID: 13d335342c43
Revises: d58da8be2931
Create Date: 2026-04-06 15:19:03.378390

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13d335342c43"
down_revision: str | Sequence[str] | None = "d58da8be2931"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "price_registration", "registered_by", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError
