"""Add Station table

Revision ID: 1f79f11dbbf0
Revises: e34b89f7b41a
Create Date: 2026-04-02 10:33:14.216586

"""

from collections.abc import Sequence

import sqlalchemy as sa
from geoalchemy2 import Geography

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f79f11dbbf0"
down_revision: str | Sequence[str] | None = "e34b89f7b41a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "station",
        sa.Column("osm_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "AUTOMAT_1",
                "BEST",
                "BUNKER_OIL",
                "CIRCLE_K",
                "DRIV",
                "ESSO",
                "HALTBAKK_EXPRESS",
                "ST1",
                "TANKEN",
                "UNO_X",
                "YX",
                "YX_TRUCK",
                name="providertype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column(
            "location",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "_inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address", "city", name="uq_station_address_city"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("osm_id"),
    )
    op.create_index(
        "idx_station_location",
        "station",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "uq_station_location",
        "station",
        [sa.literal_column("ST_AsText(location::geometry)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError
