"""Add cascade delete on favorite_station foreign keys

Revision ID: 58d1815b1a06
Revises: c47a8decb3ce
Create Date: 2026-04-19 13:35:08.133882

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58d1815b1a06"
down_revision: str | Sequence[str] | None = "c47a8decb3ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("favorite_station_station_id_fkey"),
        "favorite_station",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("favorite_station_user_id_fkey"),
        "favorite_station",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "favorite_station",
        "station",
        ["station_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "favorite_station",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "favorite_station_user_id_fkey",
        "favorite_station",
        type_="foreignkey",
    )
    op.drop_constraint(
        "favorite_station_station_id_fkey",
        "favorite_station",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("favorite_station_user_id_fkey"),
        "favorite_station",
        "user",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("favorite_station_station_id_fkey"),
        "favorite_station",
        "station",
        ["station_id"],
        ["id"],
    )
    # ### end Alembic commands ###
