"""add on delete constraints to price registrations and favorite stations

Revision ID: 5cbefe49984e
Revises: 58d1815b1a06
Create Date: 2026-04-19 18:07:43.551223

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cbefe49984e"
down_revision: str | Sequence[str] | None = "58d1815b1a06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("price_registration_registered_by_fkey"),
        "price_registration",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "price_registration",
        "user",
        ["registered_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "price_registration", type_="foreignkey")
    op.create_foreign_key(
        op.f("price_registration_registered_by_fkey"),
        "price_registration",
        "user",
        ["registered_by"],
        ["id"],
    )
    # ### end Alembic commands ###
