"""Add PriceRegistration table

Revision ID: a7f0f1f8921c
Revises: 1f79f11dbbf0
Create Date: 2026-04-03 22:49:30.157008

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7f0f1f8921c"
down_revision: str | Sequence[str] | None = "1f79f11dbbf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_registration",
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fuel_type",
            sa.Enum(
                "DIESEL",
                "GASOLINE_95",
                "GASOLINE_98",
                name="fueltype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "USER", name="priceregistrationsourcetype", native_enum=False, length=50
            ),
            server_default="USER",
            nullable=False,
        ),
        sa.Column(
            "is_latest", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "_inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["station.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_price_registration_latest_per_station_fuel",
        "price_registration",
        ["station_id", "fuel_type"],
        unique=True,
        postgresql_where=sa.text("is_latest = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError
