"""Add cascade delete on price_registration.station_id

Revision ID: c47a8decb3ce
Revises: 4d5d7e759be5
Create Date: 2026-04-16 21:30:42.088817

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c47a8decb3ce"
down_revision: str | Sequence[str] | None = "4d5d7e759be5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("price_registration_station_id_fkey"),
        "price_registration",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "price_registration",
        "station",
        ["station_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None,
        "price_registration",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("price_registration_station_id_fkey"),
        "price_registration",
        "station",
        ["station_id"],
        ["id"],
    )
    # ### end Alembic commands ###
