"""add notification tables

Revision ID: f021d088de12
Revises: 0c8c4dd9b6a2
Create Date: 2026-04-25 16:57:27.447944

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f021d088de12"
down_revision: str | Sequence[str] | None = "0c8c4dd9b6a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_alert",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=True),
        sa.Column(
            "fuel_type",
            sa.Enum(
                "DIESEL",
                "GASOLINE_95",
                "GASOLINE_98",
                name="fueltype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("threshold_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "_inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["station_id"], ["station.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "station_id",
            "fuel_type",
            name="uq_price_alert_user_station_fuel",
        ),
    )
    op.create_index(
        "uq_price_alert_user_fuel_no_station",
        "price_alert",
        ["user_id", "fuel_type"],
        unique=True,
        postgresql_where=sa.text("station_id IS NULL"),
    )
    op.create_table(
        "user_fcm_token",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("IOS", "ANDROID", name="platform", native_enum=False, length=50),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "_inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_fcm_token")
    op.drop_index(
        "uq_price_alert_user_fuel_no_station",
        table_name="price_alert",
        postgresql_where=sa.text("station_id IS NULL"),
    )
    op.drop_table("price_alert")
    # ### end Alembic commands ###
